services:
  webapp:
      build: .
      ports:
        - "8006:8000"
      volumes:
        - ./sessions:/app/sessions
        - ./data:/app/data
        - /home/joris/.claude:/app/.claude
        - /home/joris/.claude.json:/app/.claude.json
      user: "100000:100000"
      env_file:
        - ./.env
      restart: unless-stopped
